config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'blog_post/new', to: 'blog_post#new', as: :new_blog_post
  get 'blog_post/:id', to: 'blog_post#show', as: :blog_post
  get 'blog_post/:id/edit', to: 'blog_post#edit', as: :edit_blog_post
  patch 'blog_post/:id', to: 'blog_post#update'
  delete 'blog_post/:id', to: 'blog_post#destroy'
  get 'blog_posts/index'
  post 'blog_posts', to: 'blog_post#create', as: :blog_posts
  
  # resources :blog_post
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "blog_post#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_rich_text :content

    validates :title, presence: true
    validates :content, presence: true

    scope :sorted, -> { order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc)}
    scope :draft, -> { where(published_at: nil)}
    scope :published, -> { where("published_at <= ?", Time.current)}
    scope :scheduled, -> { where("published_at > ?", Time.current)}

    def draft?
      published_at.nil?
    end

    def published?
      published_at? && published_at <= Time.current
    end

    def scheduled?
      published_at? && published_at > Time.current
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
  before_action :authenticate_user!, except: [:show,:index]
  before_action :set_blog_post, except: [:index,:new,:create], except: [:index, :new]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted

    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    params[:page] = 1
    retry
  end

  def show
    # @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    # @blog_post = BlogPost.find(params[:id])  
  end

  def update
    # @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    # @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_post/_form.html.erb
<%= form_with model: @blog_post do |form|%>
<div>
    <% if form.object.errors.any? %>
        <% form.object.errors.full_messages.each do |message| %>
        <div>
            <%= message%>
        </div>
        <% end %>
    <% end %>
</div>
<div>
  <h1><%= form.label :title%></h1>
  <p><%= form.text_field :title %></p>
</div>
<div>
  <h1><%= form.label :content%></h1>
  <p><%= form.rich_text_area :content %></p>
</div>
<div>
  <h1><%= form.label :published_at%></h1>
  <p><%= form.datetime_select :published_at , include_blank: true%></p>
</div>
<%= form.button %>
<% end %>

app/views/blog_post/create.html.erb
<h1>BlogPost#create</h1>
<p>Find me in app/views/blog_post/create.html.erb</p>

app/views/blog_post/edit.html.erb
<h1>Edit Blog Post</h1>
<%= render partial: 'form', locals: {blog_post: @blog_post} %>

<%= button_to "Detele" , @blog_post, method: :delete, data:{turbo_confirm: "Are You Sure?"} %>

app/views/blog_post/index.html.erb
<h1>BlogPost#index</h1>
<% @blog_posts.each do |post|%>
<h2 ><%= link_to post.title, post%></h2>
<% if post.draft? %>
    <div class="text-gray-900">Draft</div>
<% elsif post.scheduled? %>
    <div class="text-blue-900">Scheduled</div>
<% end %>
<p><%= post.content%></p>
<% end %>

<%# Render a view helper in your views (skipping nav links for empty pages) %>
<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

<% if user_signed_in? %>
    <%= link_to "new post", new_blog_post_path%>
<% end %>

app/views/blog_post/new.html.erb
<h1>BlogPost#new</h1>

<%= render partial: 'form', locals: {blog_post: @blog_post} %>

app/views/blog_post/show.html.erb
<h1>BlogPost#show <%= @blog_post.id%></h1>
<h1><%= @blog_post.title%></h1>
<p><%= @blog_post.content %></p>

<%= link_to "edit", edit_blog_post_path(@blog_post) if user_signed_in?%>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto mb-16">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
        <%= link_to "Profile", edit_user_registration_path%>
        <%= button_to "Log out", destroy_user_session_path, method: :delete%>
      <% else %>
        <%= link_to "Log In", new_user_session_path%>
        <%= link_to "Sigup Up", new_user_registration_path%>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>